# -*- coding: utf-8 -*-
"""EV Car data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11M_p47EzTYaTTVJg2IDOeUEkXWm9kwt6
"""

import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor

data=pd.read_csv('/content/ElectricCarData_Clean.csv')
data.head(5)

data.info()

data=data.rename(columns={'AccelSec':'Accel_sec','TopSpeed_KmH':'TopSpeed_km/h','Range_Km':'Range_km','Efficiency_WhKm':'Efficiency_wh/km','FastCharge_KmH':'FastCharge_km/h'})

data.head()

data.shape

data['Accel_sec']=data['Accel_sec'].astype(str).str.replace('sec','')
data['TopSpeed_km/h']=data['TopSpeed_km/h'].astype(str).str.replace('km/h','')
data['Range_km']=data['Range_km'].astype(str).str.replace('km','')
data['Efficiency_wh/km']=data['Efficiency_wh/km'].astype(str).str.replace('wh/km','').str.replace('Wh/km','')
data['FastCharge_km/h']=data['FastCharge_km/h'].astype(str).str.replace('km/h','').str.replace('-','434')

data['Accel_sec']=data['Accel_sec'].astype(float)
data['TopSpeed_km/h']=data['TopSpeed_km/h'].astype(int)
data['Range_km']=data['Range_km'].astype(int)
data['Efficiency_wh/km']=data['Efficiency_wh/km'].astype(float)
data['FastCharge_km/h']=data['FastCharge_km/h'].astype(int)

data.info()

data['Brand_model']=data['Brand']+''+data['Model']

nomer_data=data.select_dtypes(exclude='object')
categorecal_data=data.select_dtypes(include='object')

corrr=nomer_data.corr()

corrr=nomer_data.corr()

sns.heatmap(corrr,annot=True)
plt.title("Correlation Heatmap")
plt.show()

sns.histplot(data['PriceEuro'])

plt.figure(figsize=(10, 8))

plt.subplot(2, 2, 1)
sns.boxplot(y=data['PriceEuro'])
plt.title('Price (Euro)')

plt.subplot(2, 2, 2)
sns.boxplot(y=data['Range_km'])
plt.title('Range (km)')

plt.subplot(2, 2, 3)
sns.boxplot(y=data['Accel_sec'])
plt.title('Accel_sec')

plt.subplot(2, 2, 4)
sns.boxplot(y=data['TopSpeed_km/h'])
plt.title('TopSpeed_km/h')

top_accel = data.groupby('Brand')['Accel_sec'].min().sort_values(ascending=True).head(10)

sns.barplot(x=top_accel.index, y=top_accel.values)

plt.xticks(rotation=45, ha='right')
plt.title("Top 10 Brands with Best Acceleration Time")
plt.xlabel("Brand")
plt.ylabel("Best Acceleration Time (sec)")
plt.show()

top_accel = data.groupby('Brand_model')['Accel_sec'].mean().sort_values().head(10)

sns.barplot(top_accel)
plt.xticks(rotation=45, ha='right')

TopSpeed_km = data.groupby('Brand_model')['TopSpeed_km/h'].mean().sort_values(ascending=False).head(10)

sns.barplot(TopSpeed_km)
plt.xticks(rotation=45, ha='right')

import seaborn as sns
import matplotlib.pyplot as plt
sns.scatterplot(x='FastCharge_km/h', y='PriceEuro', data=data)
plt.title("Relationship between FastCharge_km/h and PriceEuro")
plt.xlabel("Fast Charge (km/h)")
plt.ylabel("Price (Euro)")

plt.show()

fast_but_cheap = data[(data['Accel_sec'] < 4) & (data['PriceEuro'] < 70000)]
fast_but_cheap

slost_car=data.groupby('Brand_model')['Accel_sec'].mean().sort_values(ascending=False).head(10)
sns.barplot(slost_car)
plt.xticks(rotation=45,ha='right')

Range_km = data.groupby('Brand_model')['Range_km'].mean().sort_values(ascending=False).head(10)

sns.barplot(Range_km)
plt.xticks(rotation=45, ha='right')

plt.figure(figsize=(10, 6))
sns.scatterplot(data=data, x='PlugType', y='FastCharge_km/h', hue='PlugType', palette='Set2')
plt.title('Relationship between PlugType and FastCharge (km/h)')
plt.ylabel('Fast Charge (km/h)')
plt.xlabel('Plug Type')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

PlugType_count = data['PlugType'].value_counts()
BodyStyle_count = data['BodyStyle'].value_counts()
Segment_count = data['Segment'].value_counts()
Seats_count = data['Seats'].value_counts()
RapidCharge_count = data['RapidCharge'].value_counts()
PowerTrain_count = data['PowerTrain'].value_counts()

plt.figure(figsize=(15,10))

plt.subplot(2, 3, 1)
plt.pie(PlugType_count, labels=PlugType_count.index, autopct='%1.1f%%', colors=sns.color_palette('pastel'))
plt.title('Plug Type Distribution')

plt.subplot(2, 3, 2)
plt.pie(BodyStyle_count, labels=BodyStyle_count.index, autopct='%1.1f%%', colors=sns.color_palette('pastel'))
plt.title('Body Style Distribution')

plt.subplot(2, 3, 3)
plt.pie(Segment_count, labels=Segment_count.index, autopct='%1.1f%%', colors=sns.color_palette('pastel'))
plt.title('Segment Distribution')

plt.subplot(2, 3, 4)
plt.pie(Seats_count, labels=Seats_count.index, autopct='%1.1f%%', colors=sns.color_palette('pastel'))
plt.title('Seats Distribution')

plt.subplot(2, 3, 5)
plt.pie(RapidCharge_count, labels=RapidCharge_count.index, autopct='%1.1f%%', colors=sns.color_palette('pastel'))
plt.title('Rapid Charge Distribution')

plt.subplot(2, 3, 6)
plt.pie(PowerTrain_count, labels=PowerTrain_count.index, autopct='%1.1f%%', colors=sns.color_palette('pastel'))
plt.title('Power Train Distribution')

plt.tight_layout()

plt.show()

encoder = LabelEncoder()
categorecal_data_encoded = categorecal_data.apply(encoder.fit_transform)

merged_data=pd.concat([nomer_data,categorecal_data_encoded], axis=1)

merged_data=merged_data.drop(columns='Brand_model')

scaler = StandardScaler()
scaled_data = scaler.fit_transform(merged_data)

scaled_data_df = pd.DataFrame(scaled_data, columns=merged_data.columns)

X = scaled_data_df.drop('PriceEuro', axis=1)
y = scaled_data_df['PriceEuro']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'Mean Squared Error: {mse}')
print(f'R-squared: {r2}')

rf_model = RandomForestRegressor(random_state=42)
rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)

print("Random Forest Regressor:")
print("MSE:", mean_squared_error(y_test, y_pred_rf))
print("R2:", r2_score(y_test, y_pred_rf))
